FROM php:8.2-apache

# Instalar extensiones
RUN apt-get update && apt-get install -y unzip git libzip-dev zip \
    && docker-php-ext-install pdo pdo_mysql zip \
    && a2enmod rewrite

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copiar Laravel
COPY ../backend/ /var/www/html/

# Permisos
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80
CMD ["apache2-foreground"]
